# Based on https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
blueprint:
  name: Motion-activated Light (with TimeOfDate brightness)
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/TerryvanWalen/home_assistant/blueprints/motion_light_timeofdate.yaml
  author: Terry van Walen
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
          - device_class: occupancy
            domain: binary_sensor
          - device_class: motion
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
          - domain: light
    day_start:
      name: Day start time
      default: "07:30:00"
      selector:
        time: {}
    day_brightness:
      name: Day brightness
      default: 70
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    day_wait:
      name: Day wait time
      description: Time to leave the light on after last motion is detected.
      default: 420
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
    evening_start:
      name: Evening start time
      default: "20:00:00"
      selector:
        time: {}
    evening_brightness:
      name: Evening brightness
      default: 40
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    evening_wait:
      name: Evening wait time
      description: Time to leave the light on after last motion is detected.
      default: 420
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
    night_start:
      name: Night start time
      default: "23:00:00"
      selector:
        time: {}
    night_brightness:
      name: Night brightness
      default: 1
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    night_wait:
      name: Night wait time
      description: Time to leave the light on after last motion is detected.
      default: 420
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
    dark_start:
      name: Night start time
      default: "23:00:00"
      selector:
        time: {}
    dark_brightness:
      name: Night brightness
      default: 1
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    dark_wait:
      name: Dark wait time
      description: Time to leave the light on after last motion is detected.
      default: 420
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

triggers:
  trigger: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

actions:
  - choose:
    - conditions:
      - condition: time
        after: !input day_start
        before: !input evening_start
      sequence:
        - service: light.turn_on
          target: !input light_target
          data:
            brightness_pct: !input day_brightness
        - wait_for_trigger:
            trigger: state
            entity_id: !input motion_entity
            from: "on"
            to: "off"
        - delay: !input no_motion_wait
    - conditions:
      - condition: time
        after: !input evening_start
        before: !input night_start
      sequence:
        - service: light.turn_on
          target: !input light_target
          data:
            brightness_pct: !input evening_brightness
        - wait_for_trigger:
            trigger: state
            entity_id: !input motion_entity
            from: "on"
            to: "off"
        - delay: !input no_motion_wait
    - conditions:
      - condition: time
        after: !input night_start
        before: !input dark_start
      sequence:
        - service: light.turn_on
          target: !input light_target
          data:
            brightness_pct: !input night_brightness
        - wait_for_trigger:
            trigger: state
            entity_id: !input motion_entity
            from: "on"
            to: "off"
        - delay: !input no_motion_wait
    - conditions:
      - condition: time
        after: !input dark_start
        before: !input day_start
      sequence:
        - service: light.turn_on
          target: !input light_target
          data:
            brightness_pct: !input dark_brightness
        - wait_for_trigger:
            trigger: state
            entity_id: !input motion_entity
            from: "on"
            to: "off"
        - delay: !input no_motion_wait
  - alias: Turn off the light
    action: light.turn_off
    target: !input light_target
