# Based on https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
blueprint:
  name: Motion-activated Light (with TimeOfDate brightness)
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/TerryvanWalen/home_assistant/blueprints/motion_light_timeofdate.yaml
  author: Terry van Walen
  input:
input:
  input:
  # reusable selectors
  brightness_selector: &brightness_selector
    number:
      min: 0
      max: 100
      unit_of_measurement: "%"

  wait_selector: &wait_selector
    number:
      min: 0.0
      max: 3600.0
      unit_of_measurement: seconds

  time_selector: &time_selector
    time: {}

  # entities
  motion_entity:
    name: Motion Sensor
    selector:
      entity:
        filter:
          - device_class: occupancy
            domain: binary_sensor
          - device_class: motion
            domain: binary_sensor

  light_target:
    name: Light
    selector:
      target:
        entity:
          - domain: light

  # Day
  day_section:
    name: Day
    icon: mdi:white-balance-sunny
    collapsed: true

  day_start:
    name: Start time
    default: "07:15:00"
    selector: *time_selector

  day_brightness:
    name: Brightness
    default: 80
    selector: *brightness_selector

  day_wait:
    name: Wait time
    default: 420
    selector: *wait_selector

  # Evening
  evening_section:
    name: Evening
    icon: mdi:weather-sunset
    collapsed: true

  evening_start:
    name: Start time
    default: "19:00:00"
    selector: *time_selector

  evening_brightness:
    name: Brightness
    default: 40
    selector: *brightness_selector

  evening_wait:
    name: Wait time
    default: 420
    selector: *wait_selector

  # Night
  night_section:
    name: Night
    icon: mdi:weather-night
    collapsed: true

  night_start:
    name: Start time
    default: "23:00:00"
    selector: *time_selector

  night_brightness:
    name: Brightness
    default: 1
    selector: *brightness_selector

  night_wait:
    name: Wait time
    default: 420
    selector: *wait_selector

  # Dark
  dark_section:
    name: Dark
    icon: mdi:brightness-2
    collapsed: true

  dark_start:
    name: Start time
    default: "23:45:00"
    selector: *time_selector

  dark_brightness:
    name: Brightness
    default: 0
    selector: *brightness_selector

  dark_wait:
    name: Wait time
    default: 0
    selector: *wait_selector

mode: restart
max_exceeded: silent

triggers:
  trigger: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

variables:
  period_values: >
    {% if day_start <= now().strftime("%H:%M") < evening_start %}
      [{{ day_brightness }}, {{ day_no_motion_wait }}]
    {% elif evening_start <= now().strftime("%H:%M") < night_start %}
      [{{ evening_brightness }}, {{ evening_no_motion_wait }}]
    {% elif night_start <= now().strftime("%H:%M") < dark_start %}
      [{{ night_brightness }}, {{ night_no_motion_wait }}]
    {% else %}
      [{{ dark_brightness }}, {{ dark_no_motion_wait }}]
    {% endif %}
  brightness: "{{ period_values[0] }}"
  wait_time: "{{ period_values[1] }}"
  
actions:
  - service: light.turn_on
    target: !input light_target
    data:
      brightness_pct: "{{ brightness }}"
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_entity
        from: "on"
        to: "off"
  - delay: "{{ wait_time }}"
  - alias: Turn off the light
    service: light.turn_off
    target: !input light_target