# Based on https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
blueprint:
  homeassistant:
    min_version: 2024.10.0
  name: Motion-activated Light (with TimeOfDate brightness)
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/TerryvanWalen/home_assistant/blueprints/motion_light_timeofdate.yaml
  author: Terry van Walen
  input:
    # entities
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
          - device_class: occupancy
            domain: binary_sensor
          - device_class: motion
            domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
          - domain: light

    # Sections
    day_section:
      name: Day
      icon: mdi:white-balance-sunny
      collapsed: false
      input:
        day_start:
          name: Start time
          default: "07:15:00"
          selector: &time_selector
            time: {}
        day_brightness:
          name: Brightness
          default: 80
          selector: &brightness_selector
            number:
              min: 0
              max: 100
              unit_of_measurement: "%"
        day_wait:
          name: Wait time
          default: 420
          selector: &wait_selector
            number:
              min: 0.0
              max: 3600.0
              unit_of_measurement: seconds

    evening_section:
      name: Evening
      icon: mdi:weather-sunset
      collapsed: false
      input:
        evening_start:
          name: Start time
          default: "19:00:00"
          selector: *time_selector
        evening_brightness:
          name: Brightness
          default: 40
          selector: *brightness_selector
        evening_wait:
          name: Wait time
          default: 420
          selector: *wait_selector

    night_section:
      name: Night
      icon: mdi:weather-night
      collapsed: false
      input:
        night_start:
          name: Start time
          default: "23:00:00"
          selector: *time_selector
        night_brightness:
          name: Brightness
          default: 1
          selector: *brightness_selector
        night_wait:
          name: Wait time
          default: 420
          selector: *wait_selector

    dark_section:
      name: Dark
      icon: mdi:brightness-2
      collapsed: false
      input:
        dark_start:
          name: Start time
          default: "23:45:00"
          selector: *time_selector
        dark_brightness:
          name: Brightness
          default: 0
          selector: *brightness_selector
        dark_wait:
          name: Wait time
          default: 0
          selector: *wait_selector

mode: restart
max_exceeded: silent

triggers:
  trigger: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

variables:
  now_time: "{{ now().strftime('%H:%M:%S') }}"
  period_values: >
    {% if day_start <= now_time < evening_start %}
      [{{ day_brightness }}, {{ day_wait }}]
    {% elif evening_start <= now_time < night_start %}
      [{{ evening_brightness }}, {{ evening_wait }}]
    {% elif night_start <= now_time < dark_start %}
      [{{ night_brightness }}, {{ night_wait }}]
    {% else %}
      [{{ dark_brightness }}, {{ dark_wait }}]
    {% endif %}
  brightness: "{{ period_values[0] }}"
  wait_time: "{{ period_values[1] }}"
  
actions:
  - service: light.turn_on
    target: !input light_target
    data:
      brightness_pct: "{{ brightness }}"
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_entity
        from: "on"
        to: "off"
  - delay: "{{ wait_time }}"
  - alias: Turn off the light
    service: light.turn_off
    target: !input light_target